### ISSUE TITLE
files on GitHub and PyPI are different

### ISSUE THREAD

**Issue by kinoshitadaisuke** [neuromorphicsystems/astrometry#4]
Hello,

I tried to install astrometry 4.1.1, and have found that files downloaded from GitHub and PyPI are different.
The file astrometry-4.1.1.tar.gz on PyPi contains nearly everything, but the file "astrometry_extension/astrometry_extension_utilities.h" and the file "scripts/plot_distortion.py" are missing.
The file astrometry-4.1.1.tar.gz on GitHub misses the file "PKG-INFO", files in the directories " astrometry.egg-info" and "astrometry.net".

Could you please check about it?

thank you,

Daisuke

**Comment by aMarcireau** [comment]
Hi @kinoshitadaisuke,

Thank you for noticing! I added "astrometry_extension/astrometry_extension_utilities.h" and "scripts/plot_distortion.py" to "MANIFEST.in", which controls which files are packaged in the source distribution on PyPI.

The source distribution "astrometry-4.1.1.tar.gz" is generated by the command `python3 setup.py sdist`. Besides copying the project files, the command creates a few extra files (including PKG-INFO and astrometry.egg).

Github generates "astrometry-4.1.1.tar.gz" by zipping the repository, which is why generated files are missing. "astrometry.net" is a git submodule of this repository and is not included either.

If you want to build a copy of astrometry from source or edit this repository, you should download the PyPI source distribution file or use `git clone --recursive https://github.com/neuromorphicsystems/astrometry.git` to copy this repository with the astrometry submodule.

Cheers,
Alex
